services:
  - type: web
    name: clandestino-proxy
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python proxy.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
